<?php
$this->addJs($this->options->themeUrl . '/js/vendor/jquery.iframe-transport.js');
$this->addJs($this->options->themeUrl . '/js/vendor/jquery.fileupload.js');
$this->addMeta('allowedImageFormats', implode($config->acceptedImageFormats, ','));
if (class_exists('AttachCaptions')) {
  $this->addMeta('allowedCaptionFormats', implode($config->acceptedCaptionFormats, ','));
}
$this->addMeta('tempDirUrl', getTempDirUrl($loggedInUser));
$this->addJs($this->options->themeUrl . '/js/vendor/jsrender.min.js');
$this->addJs('general.js');
$this->addJs('fileupload.js');
$this->setLayout('account');
?>

<div class="row">
  <div class="col header-secondary">
    <h2><?= Language::getText('upload_header') ?></h2>
    <?php (isset($message)) ? showAlertMessage($message, $message_type) : ''; ?>
  </div>
</div>

<div class="row">
  <div class="col">
    <form action="<?= HOST ?>/account/upload/info/" method="post" enctype="multipart/form-data">
      <!-- BEGIN Basic Information Tab -->
      <div class="row">
        <div class="col-md-6">
          <h4 class="text-white bg-secondary p-2" id="basic-information"><?php echo Language::getText('video_basic_tab_header'); ?></h4>

          <label for="title"><?= Language::getText('title') ?></label>
          <input type="text" class="form-control <?= (isset($errors['title'])) ? ' is-invalid' : '' ?>" name="title" id="title" placeholder="<?= Language::getText('title') ?>" value="<?= (!empty($video->title)) ? $video->title : '' ?>">

          <label for="description"><?= Language::getText('description') ?></label>
          <textarea name="description" class="form-control<?= (isset($errors['description'])) ? ' is-invalid' : '' ?>" id="description" rows="3" cols="100"><?= (!empty($video->description)) ? $video->description : '' ?></textarea>

          <label for="tags"><?= Language::getText('tags') ?></label>
          <input type="text" class="form-control <?= (isset($errors['tags'])) ? ' is-invalid' : '' ?>" name="tags" id="tags" placeholder="i.e. a, comma, separated, list, of, tags" value="<?= (!empty($video->tags)) ? implode(', ', $video->tags) : '' ?>">

          <label for="category"><?= Language::getText('category') ?></label>
          <select class="custom-select <?= (isset($errors['cat_id'])) ? ' is-invalid' : '' ?>" id="category" name="cat_id">
            <?php foreach ($categoryList as $category) : ?>
              <option<?= (!empty($video->categoryId) && $category->categoryId == $video->categoryId) ? ' selected="selected"' : '' ?> value="<?= $category->categoryId ?>"><?= $category->name ?></option>
              <?php endforeach; ?>
          </select>

          <!-- END Basic Information -->
          <!-- BEGIN Settings -->
          <div id="advanced-settings" class="py-4">
            <h4 class="text-white bg-secondary p-2" id="advanced-settings"><?php echo Language::getText('video_advanced_tab_header'); ?></h4>

            <ul class="list-group">
              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="disable_embed" name="disable_embed" <?= (!empty($video->disableEmbed)) ? 'checked="checked"' : '' ?>>
                  <label class="custom-control-label" for="disable_embed"><?= Language::getText('disable_embed') ?></label> (<?= Language::getText('disable_embed_description') ?>)
                </div>
              </li>

              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="gated" name="gated" <?= (isSetByDefault('gated')) ? ' checked' : '' ?>>
                  <label class="custom-control-label" for="gated"><?= Language::getText('gated') ?></label> (<?= Language::getText('gated_description') ?>)
                </div>
              </li>

              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="private_video" data-block="private_url" name="private" <?= (isSetByDefault('private')) ? ' checked' : '' ?> data-toggle="collapse" data-target="#showPrivateLink" aria-expanded="false" aria-controls="showPrivateLink">
                  <label class="custom-control-label" for="private_video"><?= Language::getText('private') ?></label> (<?= Language::getText('private_description') ?>)
                  <div id="showPrivateLink" class="collapse<?= (isSetByDefault('private')) ? ' show' : '' ?>" aria-labelledby="private_video">
                    <label class="<?= (isset($errors['private_url'])) ? 'error' : '' ?>"><?= Language::getText('private_url') ?>:</label><br />
                    <input class="form-control" type="text" id="privateLink" value="<?= HOST ?>/private/videos/<?= (!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl ?>/" readonly>
                    <input type="hidden" id="private_url" name="private_url" value="<?= (!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl ?>" />
                    <p class="text-right pt-2">
                      <button type="button" id="regenerate" class="btn btn-sm btn-outline-primary"><?= Language::getText('regenerate') ?></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary btn-clipboard" data-clipboard-target="#privateLink">Copy to Clipboard</button>
                    </p>
                  </div>
                </div>
                <?= Language::getText('upload_info_privacy_end') ?>
              </li>
              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="closeComments" name="closeComments" <?= (!empty($video->commentsClosed)) ? 'checked="checked"' : '' ?>>
                  <label class="custom-control-label" for="closeComments"><?= Language::getText('closeComments') ?></label> (<?= Language::getText('closeCommentsDescription') ?>)
                </div>
              </li>
          </div>
          <!-- END Settings -->
        </div>
        <div class="form-group col-md-6">

          <!-- BEGIN Attachments Section -->
          <div id="video-attachments">
            <?php if ($config->allowVideoAttachments) : ?>
              <h4 class="text-white bg-secondary p-2" id="video-attachments"><?php echo Language::getText('video_attachments_tab_header'); ?></h4>
              <p class="video-attachments-tab-desc"><?php echo Language::getText('video_attachments_tab_help'); ?></p>
              <ul class="attachments list-group">
                <?php $attachmentCount = 0; ?>
                <?php foreach ($newFiles as $newFile) : ?>
                  <li class="media border-top mt-1 py-2 attachment">
                    <?php echo attachmentItem(array("name" => $newFile['name'], "size" => $newFile['size'], "temp" => $newFile['temp']), $attachmentCount, true); ?>
                    <div class="upload-ready d-flex bg-dark justify-content-center mr-2 related-thumb-container">
                      <?= attachmentIcon($newFile['temp']); ?>
                    </div>
                    <div class="media-body">
                      <p class="mt-0 mb-1">
                        <span class="filename-attached"><span class="attachment-file-name"><?= $newFile['name'] ?></span> <span class="attachment-filesize"> (<?= \Functions::formatBytes($newFile['size'], 0); ?>) </span><a class="float-right btn btn-sm btn-outline-danger remove" href="#" role="button">Remove</a>
                        <?php Plugin::triggerEvent('videos.edit.attachment.list', $newFile['temp'], $video->videoId); ?>
                      </p>
                    </div>
                  </li>
                  <?php $attachmentCount++; ?>
                <?php endforeach; ?>

                <?php foreach ($newAttachmentFileIds as $fileId) : ?>
                  <?php $file = \Functions::arrayColumnFilter($fileId, 'fileId', $userAttachments); ?>
                  <li class="media border-top mt-1 py-2 attachment existing-file" id="existing-file-<?php echo $fileId; ?>">
                    <div class="upload-ready d-flex bg-dark justify-content-center mr-2 related-thumb-container">
                      <?= attachmentIcon($fileId); ?>
                    </div>
                    <div class="media-body">
                      <p class="mt-0 mb-1">
                        <span class="filename-attached"><span class="attachment-file-name"><?= $file[0]->name ?> </span> <span class="attachment-filesize">(<?= \Functions::formatBytes($file[0]->filesize, 0); ?>) </span><a class="float-right btn btn-sm btn-outline-danger remove" href="#" role="button">Remove</a>
                        <?php Plugin::triggerEvent('videos.edit.attachment.list', $file[0]->fileId, $video->videoId); ?>
                      </p>
                      <?php echo attachmentItem(array("name" => $file[0]->name, "size" => $file[0]->filesize, "file" => $file[0]->fileId), $attachmentCount, false); ?>
                    </div>
                  </li>
                  <?php $attachmentCount++; ?>
                <?php endforeach; ?>
              </ul>
              <div class="attachment-form attachment-form-upload pt-3">

                <h5><?php echo Language::getText('upload_new_attachment_header'); ?></h5>

                <div class="custom-file">
                  <input class="uploader custom-file-input form-control" id="upload" type="file" name="attachment-upload" data-url="<?php echo BASE_URL; ?>/ajax/upload/" data-text="<?php echo Language::getText('browse_files_button'); ?>" data-limit="<?php echo $config->fileSizeLimit; ?>" data-type="library" />
                  <label class="custom-file-label" for="upload">Choose file</label>
                </div>
              </div>
              <?php if (!empty($userAttachments)) : ?>
                <div class="attachment-form-existing mt-3">
                  <h5><?php echo Language::getText('select_existing_attachment_header'); ?></h5>
                  <p><?php echo Language::getText('select_existing_attachment_help'); ?></p>
                  <ul class="list-group">
                    <?php foreach ($userAttachments as $file) : ?>
                      <li class="media border-top mt-1 py-2<?= (in_array($file->fileId, $newAttachmentFileIds)) ? ' d-none' : ''; ?>">
                        <div class="d-flex bg-dark justify-content-center mr-2 related-thumb-container">
                          <?= attachmentIcon($file->fileId); ?>
                        </div>
                        <div class="media-body">
                          <p class="mt-0 mb-1">
                            <span class="filename-attached"><span class="attachment-file-name"><?= $file->name ?></span> <span class="attachment-filesize">(<?= \Functions::formatBytes($file->filesize, 0); ?>) </span> <a id="select-existing-file-<?php echo $file->fileId; ?>" class="float-right btn btn-sm <?php echo in_array($file->fileId, $newAttachmentFileIds) ? 'btn-outline-danger' : 'btn-outline-primary'; ?>" href="" data-file="<?php echo $file->fileId; ?>" data-size="<?php echo $file->filesize; ?>" title="<?php echo $file->name; ?>"><?php echo in_array($file->fileId, $newAttachmentFileIds) ? 'Remove' : 'Add'; ?></a>
                          </p>
                        </div>
                      </li>
                    <?php endforeach; ?>
                  </ul>
                </div>
                <?php Plugin::triggerEvent('videos.edit.attachment.end'); ?>
              <?php endif; ?>
          </div>
        <?php endif; ?>
        <!-- END Attachment Section -->
        </div>
      </div>
      <input type="hidden" name="submitted" value="TRUE" />
      <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
      <button type="submit" class="btn btn-primary"><?= Language::getText('upload_video_button') ?></button>
    </form>
  </div>
</div>
